# Generated by Django 4.2.3 on 2023-10-12 15:23

from django.db import migrations, models
import shopapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0015_order_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview1',
            field=models.ImageField(blank=True, null=True, upload_to=shopapp.models.product_preview_directory_path),
        ),
    ]
