# Generated by Django 4.2.3 on 2023-11-01 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0019_alter_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price'], 'permissions': (('create_product', 'update_product'),), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
